# Generated by Django 4.2.25 on 2025-11-14 01:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('calorias', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('img', models.ImageField(blank=True, max_length=500, null=True, upload_to='historial_comidas/')),
                ('nombre_alimento', models.CharField(max_length=255)),
                ('cantidad_consumida', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('tipo_comida', models.CharField(blank=True, choices=[('DESAYUNO', 'Desayuno'), ('ALMUERZO', 'Almuerzo'), ('CENA', 'Cena'), ('SNACK', 'Snack')], max_length=10, null=True)),
                ('metodo_registro', models.CharField(choices=[('ESCANEADO', 'Escaneado'), ('MANUAL', 'Manual'), ('PLAN', 'Plan')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
