# Generated by Django 4.2.25 on 2025-11-14 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_historialmodel_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historialmodel',
            options={'ordering': ['-fecha'], 'verbose_name': 'Historial de Comida', 'verbose_name_plural': 'Historial de Comidas'},
        ),
        migrations.AddField(
            model_name='historialmodel',
            name='carbohidratos',
            field=models.FloatField(blank=True, help_text='Carbohidratos en gramos', null=True),
        ),
        migrations.AddField(
            model_name='historialmodel',
            name='grasas',
            field=models.FloatField(blank=True, help_text='Grasas en gramos', null=True),
        ),
        migrations.AddField(
            model_name='historialmodel',
            name='proteinas',
            field=models.FloatField(blank=True, help_text='Proteínas en gramos', null=True),
        ),
        migrations.AlterModelTable(
            name='historialmodel',
            table='historial',
        ),
    ]
