# Generated by Django 4.2.25 on 2025-10-15 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('peso', models.FloatField(verbose_name=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Peso'))),
                ('altura', models.FloatField(verbose_name=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Altura'))),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('fech_cumpleanos', models.DateField()),
                ('entrenamiento', models.CharField(choices=[('Muy activo', 'Muy activo'), ('Activo', 'Activo'), ('Moderado', 'Moderado'), ('Sedentario', 'Sedentario')], max_length=20)),
            ],
        ),
    ]
