# Generated by Django 4.2.25 on 2025-11-13 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='ID único de sesión para usuarios anónimos', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, help_text='Para usuarios anónimos', max_length=255, null=True)),
                ('objetivo_calorias_diarias', models.IntegerField(blank=True, help_text='Calorías objetivo por día', null=True)),
                ('objetivo_peso', models.FloatField(blank=True, help_text='Peso objetivo en kg', null=True)),
                ('objetivo_tipo', models.CharField(blank=True, choices=[('perder', 'Perder peso'), ('mantener', 'Mantener peso'), ('ganar', 'Ganar peso')], max_length=20, null=True)),
                ('restricciones_alimentarias', models.TextField(blank=True, help_text='Alergias, intolerancias, etc.', null=True)),
                ('preferencias_dieta', models.CharField(choices=[('normal', 'Normal'), ('vegetariana', 'Vegetariana'), ('vegana', 'Vegana'), ('keto', 'Cetogénica'), ('mediterranea', 'Mediterránea')], default='normal', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('user', 'Usuario'), ('bot', 'Bot')], max_length=10)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.conversation')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
